version: 'minty.abcxyz.dev/v2'

rule:
  if: |-
    assertion.iss == issuers.github &&
    assertion.repository_owner_id == '93787867' &&
    assertion.repository_id == '966875030' &&
    assertion.workflow_ref == assertion.job_workflow_ref &&
    assertion.ref == 'refs/heads/main'

scope:
  draft-release:
    rule:
      if: |-
        assertion.workflow_ref.startsWith('abcxyz/actions/.github/workflows/draft-release.yml') &&
        assertion.event_name == 'workflow_dispatch'
    repositories:
      - 'actions'
    permissions:
      contents: 'write'
      pull_requests: 'write'

  release:
    rule:
      if: |-
        assertion.job_workflow_ref.startsWith('abcxyz/actions/.github/workflows/release.yml') &&
        assertion.event_name == 'push'
    repositories:
      - 'actions'
    permissions:
      contents: 'write'
