# Copyright 2025 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'lint-javascript'
description: 'Lint javascript against the abcxyz style guide.'
inputs:
  gts_version:
    description: 'The version of gts to use. This must be the full version with no leading "v" prefix.'
    type: 'string'
    default: '6.0.2'
  eslint_version:
    description: 'The version of eslint to use. This must be the full version with no leading "v" prefix.'
    type: 'string'
    default: '9.26.0'
  directory:
    description: 'Directory in which Java files reside.'
    type: 'string'
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: 'Is eslint'
      id: 'is-eslint'
      shell: 'bash'
      working-directory: '${{ inputs.directory }}'
      run: |
        if [[ -f  eslint.config.js ]]; then
          echo "found=true" >> "${GITHUB_OUTPUT}"
        fi

    - name: 'Install GTS'
      if: |
        steps.is-eslint.outputs.found != 'true'
      shell: 'bash'
      env:
        GTS_VERSION: '${{ inputs.gts_version }}'
      run: |
        npm install "gts@${GTS_VERSION}"

    - name: 'Install ESLINT'
      if: |
        steps.is-eslint.outputs.found == 'true'
      shell: 'bash'
      env:
        ESLINT_VERSION: '${{ inputs.eslint_version }}'
      run: |
        npm install "eslint@${ESLINT_VERSION}"

    - name: 'Check formatting'
      shell: 'bash'
      working-directory: '${{ inputs.directory }}'
      env:
        IS_ESLINT: '${{ steps.is-eslint.outputs.found }}'
      run: |-
        shopt -s globstar

        if [[ "${IS_ESLINT}" == "true" ]]; then
          npx eslint "**/*.js"
        else
          npx gts lint "**/*.js"
        fi
