# Copyright 2025 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'lint-java'
description: 'Lint java against the abcxyz style guide.'
inputs:
  java_version:
    description: 'The version of Java to install and use.'
    type: 'string'
    default: ''
  java_version_file:
    description: 'The version file to use to detect java versions.'
    type: 'string'
    default: '.java-version'
  java_distribution:
    description: 'The distibution of Java to use.'
    type: 'string'
    default: ''
  google_java_format_version:
    description: 'The version of google-java-format to use. This must be the full version with no leading "v" prefix.'
    type: 'string'
    default: '1.25.2'
  google_java_format_version_file:
    description: 'The version file with the google-java-format to use. This must be the full version with no leading "v" prefix.'
    type: 'string'
    default: '.java-version-google-format'
  directory:
    description: 'Directory in which Java files reside.'
    type: 'string'
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: 'Setup Java'
      uses: 'abcxyz/actions/.github/actions/setup-java-strict@09ff15858f2515a21985c660d771f48bfef514b6' # ratchet:exclude
      with:
        distribution: '${{ inputs.java_distribution }}'
        java-version: '${{ inputs.java_version }}'
        java-version-file: '${{ inputs.java_version_file }}'

    - name: 'Parse google java format version info'
      id: 'google-java-info'
      if: |
        inputs.google_java_format_version_file != ''
      shell: 'bash'
      env:
        GOOGLE_JAVA_FORMAT_VERSION_FILE: '${{ inputs.google_java_format_version_file }}'
      run: |
        version="$(cat "${GOOGLE_JAVA_FORMAT_VERSION_FILE}")"
        echo "version=${version}" >> "${GITHUB_OUTPUT}"

    - name: 'Download google-java-format'
      shell: 'bash'
      env:
        GOOGLE_JAVA_FORMAT_VERSION: '${{ steps.google-java-info.outputs.version || inputs.google_java_format_version }}'
      run: |-
        BIN="${{ runner.tool_cache }}/google-java-format-${GOOGLE_JAVA_FORMAT_VERSION}"

        if [[ -x "${BIN}" ]]; then
          echo "Already installed!"
        else
          curl -sLfo "${BIN}" \
            "https://github.com/google/google-java-format/releases/download/v${GOOGLE_JAVA_FORMAT_VERSION}/google-java-format-${GOOGLE_JAVA_FORMAT_VERSION}-all-deps.jar"
          chmod +x "${BIN}"
        fi

    - name: 'Check formatting'
      shell: 'bash'
      working-directory: '${{ inputs.directory }}'
      env:
        GOOGLE_JAVA_FORMAT_VERSION: '${{ steps.google-java-info.outputs.version || inputs.google_java_format_version }}'
      run: |-
        shopt -s globstar

        java -jar "${{ runner.tool_cache }}/google-java-format-${GOOGLE_JAVA_FORMAT_VERSION}" -i **/*.java

        if [ -n "$(git status -s -uall)" ]; then
          echo "::error title=Java formatting::Detected unformatted Java"
          git -c color.ui=always diff
          exit 1
        fi
