#!/bin/bash
#MISE description="Lint github workflows and actions"
#MISE quiet=true
#MISE tools={ shellcheck = "0.10.0", actionlint = "1.7.7" }
GITHUB_FORMAT='{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Filepath}}@{{$err.Line}} {{$err.Message}}%0A```%0A{{replace $err.Snippet "\\n" "%0A"}}%0A```\n{{end}}'
if [[ -n "${GITHUB_WORKSPACE}" ]]; then FORMAT="${GITHUB_FORMAT}"; else FORMAT=""; fi

actionlint \
    -color \
    -format "${FORMAT}" \
    -ignore 'SC2016:' \
    -ignore 'label ".+" is unknown'
