#!/bin/bash
#MISE description="Lint github workflows and actions"
#MISE quiet=true
actionlint \
    -color \
    -format '{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Filepath}}@{{$err.Line}} {{$err.Message}}%0A```%0A{{replace $err.Snippet "\\n" "%0A"}}%0A```\n{{end}}' \
    -ignore 'SC2016:' \
    -ignore 'label ".+" is unknown'
