#!/bin/bash
#MISE description="Lint terraform files"
#MISE quiet=true
#MISE tools={ "ubi:abcxyz/terraform-linter" = "latest" }
if which terraform; then
    terraform fmt -recursive -check
else
    echo "Skipping 'terraform fmt' because no binary was found - Did you forget to 'mise use terraform'?"
fi

git ls-files | grep -E '\.(tf)' | xargs terraform-linter lint
