# Copyright 2025 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'lint-github-actions'
description: 'Lint github actions against the abcxyz style guide.'
inputs:
  actionlint_version:
    description: 'The version of actionlint to install and use.'
    type: 'string'
    default: '1.7.7'
  actionlint_matcher_url:
    decription: 'The actionlint matcher to use for github comments.'
    type: 'string'
    default: 'https://raw.githubusercontent.com/abcxyz/actions/main/actionlint-matcher.json'

runs:
  using: 'composite'
  steps:
    - name: 'Setup Actionlint'
      uses: 'abcxyz/actions/.github/actions/setup-binary@main' # ratchet:exclude
      with:
        download_url: 'https://github.com/rhysd/actionlint/releases/download/v${{ inputs.actionlint_version }}/actionlint_${{ inputs.actionlint_version }}_linux_amd64.tar.gz'
        install_path: '${{ runner.temp }}/.actionlint'
        binary_subpath: 'actionlint'
        cache_key: '${{ runner.os }}_${{ runner.arch }}_actionlint_${{ inputs.actionlint_version }}'
        add_to_path: true
        
    - name: 'Add matcher'
      shell: 'bash'
      run: |
        # Create a unique output file outside of the checkout.
        ACTIONLINT_MATCHER_JSON="${RUNNER_TEMP}/${GITHUB_SHA:0:7}.actionlint-matcher.json"

        # Download the file, passing in authentication to get a higher rate
        # limit: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-github-actions
        curl "${{ inputs.actionlint_matcher_url }}" \
          --silent \
          --fail \
          --location \
          --header "Authorization: Token ${{ github.token }}" \
          --output "${ACTIONLINT_MATCHER_JSON}"

        matcher=".github/actionlint-matcher.json"
        echo "::add-matcher::$ACTIONLINT_MATCHER_JSON"

    - name: 'Actionlint'
      shell: 'bash'
      run: |
        actionlint
