# Copyright 2025 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'lint-terraform'
description: 'Lint terraform against the abcxyz style guide.'
inputs:
  terraform_version:
    description: 'The version of Terraform to install and use.'
    type: 'string'
    required: true
  directory:
    description: 'The directory upon which to lint Terraform configurations.'
    type: 'string'
    required: true
    default: '.'
  terraform_linter_version:
    description: 'The version of the terraform linter to install and use.'
    type: 'string'
    required: true
    default: '0.2.0'

runs:
  using: 'composite'
  steps:
    - name: 'Setup Terraform'
      uses: 'hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd' # ratchet:hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: '${{ inputs.terraform_version }}'

    - name: 'Check formatting'
      if: 'always()'
      working-directory: '${{ inputs.directory }}'
      shell: 'bash'
      run: |-
        terraform fmt -recursive -check -diff

    - name: 'Setup terraform-linter'
      uses: 'abcxyz/actions/.github/actions/setup-binary@main' # ratchet:exclude
      with:
        download_url: 'https://github.com/abcxyz/terraform-linter/releases/download/v${{ inputs.terraform_linter_version }}/terraform-linter_linux_amd64'
        install_path: '${{ runner.temp }}/.terraform-linter'
        binary_subpath: 'terraform-linter_linux_amd64'
        cache_key: '${{ runner.os }}_${{ runner.arch }}_terraform_linter_${{ inputs.terraform_linter_version }}'
        add_to_path: true
        destination_subpath: 'terraform-linter'

    - name: 'Run abcxyz/terraform-linter'
      shell: 'bash'
      env:
        LINT_PATHS: |-
          ${{ inputs.directory || '.' }}
      run: |-
        terraform-linter lint ${LINT_PATHS}
